# -*- coding: utf-8 -*-
"""kaggle_churn_modeling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17tCO-MIIW1dH5Qxbe3H57_eJ-0bNHljQ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

data = pd.read_csv('/content/drive/MyDrive/Geeta-New-Drive/kaggle data set/Churn_Modelling.csv')
data.head()

data.info()

data.shape

data['Exited'].unique()

#maping 0 and 1 to exited and stayed employees
data['Exited'] = data['Exited'].map({0 : 'Stay', 1 : 'Exited'})

#Exited and stayed in percentage
exited_proportion = data['Exited'].value_counts(normalize=True)*100
exited_proportion

ax = sns.countplot(x=data['Exited'], order=data['Exited'].value_counts().index, color='blue')
ax.bar_label(ax.containers[0])
plt.title('count of employees exit')
plt.show()


ax = exited_proportion.plot.bar(color='yellow')
ax.bar_label(ax.containers[0])
plt.xticks(rotation=0)
plt.title('percentation of employees exit')
plt.show()

data['Geography'].value_counts()

# Geographycally exited status in percentage
geography_exited = round(data.groupby('Geography')['Exited'].value_counts(normalize=True)*100,2)
geography_exited

#Boxplot for Geographycal outliers

min = data['Age'].min()
max = data['Age'].max()
q1 = data['Age'].quantile(0.25)
q2 = data['Age'].quantile(0.5)
q3 = data['Age'].quantile(0.75)

print('min: ', min)
print('max: ', max)
print('q1: ', q1)
print('q2: ', q2)
print('q3: ', q3)

iqr = q3 - q1

lower_fence = q1 - 1.5*(iqr)
upper_fence = q3 + 1.5*(iqr)

print('Lower fence is: ', lower_fence)
print('upper fence is: ', upper_fence)

sns.boxplot(x=data['Age'])
plt.title('Box plot for Age')
plt.show()

# finding where the outliers are lieaing
data['Age'].describe(percentiles=[0.25,0.5,0.75,0.8,0.85,0.9,0.95,0.98])

data['IsActiveMember'].value_counts()





data_proportion= data['Gender'].value_counts(normalize=True)*100
data_proportion

ax = data_proportion.plot.bar(color='pink')
ax.bar_label(ax.containers[0])
plt.xticks(rotation=0)
plt.title('Total percentage of Male and Female')
plt.show()

grouped=round(data.groupby('Gender')['Exited'].value_counts(normalize=True)*100,2)

grouped.plot(kind='bar', color = 'Green')
plt.title('Exited and not Exited based on Gender')
plt.xlabel('Gender')
plt.ylabel('no of employes')
plt.xticks(rotation=0)
plt.show()

data.groupby('Age')['Exited'].size()